backend:
    name: git-gateway
    branch: master
    commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
    - name: 'pages'
      label: 'Pages'
      files:
          - file: 'src/pages/index.md'
            label: 'Landing Page'
            name: 'index'
            fields:
                - {
                      label: 'Template Key',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'IndexTemplate',
                  }
                - {
                      label: Meta,
                      name: meta,
                      widget: object,
                      fields:
                          [
                              { label: Title, name: title, widget: string },
                              {
                                  label: Description,
                                  name: description,
                                  widget: text,
                              },
                          ],
                  }
                  - {
                    label: Content,
                    name: content,
                    widget: object,
                    fields:
                        [
                            { label: Heading, name: heading, widget: string },
                            {
                                label: Text,
                                name: text,
                                widget: text,
                            },
                        ],
                }